### ISSUE TITLE
Add tests for https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet

### ISSUE THREAD

**Issue by MichaelJCole** [yahoo/xss-filters#16]
Hey, I was looking through your tests and didn't see alot of XSS attacks.  But I'm a n00b on this.

I found this list of attacks that would make a great set of tests:  https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet

**Comment by adon-at-work** [comment]
We have already taken that particular list of XSS attack vectors into account during our design. So, you're assured that it's xss free with the filters applied in their desired contexts and encoding (i.e., utf-8).

Incorporating them as test cases is a big plus, I'm looking forward to external contributions before I have time doing this myself. Thanks for the suggestion. :)

**Comment by adon-at-work** [comment]
The PR https://github.com/yahoo/xss-filters/pull/22 is merged to addressed this.
