### ISSUE TITLE
Version mismatch in bower.json and package.json

### ISSUE THREAD

**Issue by amitrai99** [yahoo/xss-filters#17]
package.json 1.1.1
bower.json 1.0.4

> bower xss-filters#1.1.1     not-cached git://github.com/yahoo/xss-filters.git#1.1.1
bower xss-filters#1.1.1        resolve git://github.com/yahoo/xss-filters.git#1.1.1
bower xss-filters#1.1.1       download https://github.com/yahoo/xss-filters/archive/v1.1.1.tar.gz
bower xss-filters#1.1.1        extract archive.tar.gz
bower xss-filters#1.1.1       mismatch Version declared in the json (1.0.4) is different than the resolved one (1.1.1)
bower xss-filters#1.1.1       resolved git://github.com/yahoo/xss-filters.git#1.1.1
bower xss-filters#1.1.1        install xss-filters#1.1.1

**Comment by adon-at-work** [comment]
It doesn't hurt from getting the correct version of .js, and thus we sort of ignored bumping up the version in bower.json. But no worries, we can and will update the bower.json in future releases. :)
