### ISSUE TITLE
xss-filters and hmac

### ISSUE THREAD

**Issue by bitinn** [yahoo/xss-filters#20]
An interesting issue we encounter when using `xss-filters` is trying to get url component to stay unchanged.

Say we have an image proxy like https://github.com/atmos/camo, Which takes an url like `http://example.org/<digest>?url=<image-url>`, where `digest` is a hmac of `image-url` and some secret string, so that you can guarantee the url is generated by server.

Now since `image-url` is user input, you might want to run `uriInDoubleQuotedAttr` before putting it in the `<img src="...">`, but I tried doing that and see `uriInDoubleQuotedAttr` changed the component somehow.

So if we are to generate and filter a flickr image: https://farm1.staticflickr.com/1/106113_be9654002c.jpg

```
// before filter
https://local.dev/8ed9c616a36997f04e1fde03d7d679c684316b09/?url=https%3A%2F%2Ffarm1.staticflickr.com%2F1%2F106113_be9654002c.jpg&size=400

// after filter
https://local.dev/8ed9c616a36997f04e1fde03d7d679c684316b09/?url=https%253A%252F%252Ffarm1.staticflickr.com%252F1%252F106113_be9654002c.jpg&size=400
```

Should we apply the filter earlier by making `uriComponentInDoubleQuotedAttr` when we build the url? It does work but I am not sure if it's the safe thing to do.

PS: https://github.com/yahoo/xss-filters#warnings does the warning mean we shouldn't use this generated url in `style="background-image: url(...)"`?

**Comment by adon-at-work** [comment]
You need something like the following:
```javascript
document.write('<a href="http://example.org/' +
    uriPathInDoubleQuotedAttr(digest) +
    '?url=' + uriComponentInDoubleQuotedAttr(imageUrl) +
    '">hello</a>');
```

`uri`, `uriComponent` and `uriPath`, etc are actually referring to the location of the data binding point. Therefore, `<image-url>` is a `uriComponent` instead of `uri`.

**Comment by adon-at-work** [comment]
and please stay turned for our new filters for CSS style attributes. we're going to release them soon.

**Comment by bitinn** [comment]
Thx for the reply. so you are confirming 

```
http://example.org/' + uriPathInDoubleQuotedAttr(digest) + '?url=' + uriComponentInDoubleQuotedAttr(imageUrl)
```

is not yet safe for `style` right?
