### ISSUE TITLE
[Question] Is it production ready?

### ISSUE THREAD

**Issue by danilodeveloper** [yahoo/xss-filters#51]
Hello guys! 
Can I use this in a production system? Yahoo is using somewhere?
Tks!

**Comment by adon-at-work** [comment]
Some yahoo production systems are using it, and that we believe it's safe to do so.

We also recommend you to consider using [secure-handlebars](https://github.com/yahoo/secure-handlebars) or [express-secure-handlebars](https://github.com/yahoo/express-secure-handlebars) to make it easier, i.e., apply the filters automatically.

**Comment by danilodeveloper** [comment]
Very nice! I'll use it too! :smirk: :+1:

Thanks @adon-at-work

**Comment by danilodeveloper** [comment]
Just a point, I'm migrating from Swig.js to "something.js" template engine, after your suggestion about handlebars.js, I'll consider it. Tks again!
