### ISSUE TITLE
Travis build on Node 0.12 fails (timeout)

### ISSUE THREAD

**Issue by dmitris** [yahoo/xss-filters#59]
builds get stuck on the karma test
```
Running "karma:ci" (karma) task
No SAUCE credentials found (missing SAUCE_USERNAME and SAUCE_ACCESS_KEY env variables). Skipping SauceLabs testing.
08 06 2016 10:15:36.446:WARN [karma]: No captured browser, open http://localhost:9876/
08 06 2016 10:15:36.453:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
```

Failed builds:
https://travis-ci.org/yahoo/xss-filters/jobs/79610450
https://travis-ci.org/yahoo/xss-filters/jobs/131198435

@adon-at-work

**Comment by adon-at-work** [comment]
As far as I can remember, the default setting would skip setting the SAUCE_USERNAME AND SAUCE_ACCESS_KEY env variables for commits from non-authors. That explains why 131198435 was failed. 79610450 worked. Can you confirm if I'm right?

**Comment by adon-at-work** [comment]
Further to the timeout problem in 79610450, it reported "Android on SauceLabs failed 2 times (timeout)"
It's known to me that Android on SauceLabs are not so reliable, i.e., sometimes not starting, and thus often require another attempt. 

I probably should restart the build, but didn't bother as that particular commit has changed only the README.

**Comment by dmitris** [comment]
looks good now - https://travis-ci.org/yahoo/xss-filters, closing

**Comment by adon-at-work** [comment]
thank you @dmitris :)
