### ISSUE TITLE
$ and . (mongo)

### ISSUE THREAD

**Issue by gurumelo** [yahoo/xss-filters#61]
Hello, thanks for the module.

A little question. ¿escapes "$" or "."?

https://www.npmjs.com/package/express-mongo-sanitize

**Comment by adon-at-work** [comment]
My understanding is that this package is meant only for XSS mitigations.

Are you suggesting to also escape "$" and ".", which are specific to mongo use cases? If yes, why?

**Comment by gurumelo** [comment]
One module, one solution for all.

But you' re right. Thanks.

**Comment by gurumelo** [comment]
https://github.com/gurumelo/escape-htmlandmongo
