### ISSUE TITLE
NPM error concerning shasum failure

### ISSUE THREAD

**Issue by cerebrl** [yahoo/xss-filters#62]
My team and I are getting the below error when we do an `npm install` on our project that uses `xss-filters`. Not sure why this is happening, but if anyone has any insight into this, I would greatly appreciate it. 

It may be worth noting that we do have a private NPM registry that has pulled this in from the public registry. 

Thanks in advance for any assistance.

``` sh
npm ERR! shasum check failed for /var/folders/9x/3hwlnngj0jn80b_v8bd1crh8392g3z/T/npm-82131-5d9a3836/npm.[private-npm-registry].com/xss-filters/-/xss-filters-1.2.7.tgz
npm ERR! Expected: 59fa1de201f36f2f3470dcac5f58ccc2830b0a9a
npm ERR! Actual:   e3f620eb5b3c5f82928a72c3cda91e52f55a55a7
```

PS: This only happens with v1.2.7

**Comment by adon-at-work** [comment]
Thanks for reporting the problem.

I tried to `npm install` with the external and internal registries. Both work well from my side.

I then looked up the internet briefly on whether the problem applies to other packages too, and there it is:
https://github.com/npm/npm/issues/2701

So, it sounds like that could happen when the connection or public registry server failed somehow, when your private repo is downloading a copy of that particular version from the public.

To follow up, can you try:
- `npm install` using the public registry on your own local machine
- if that works, this probably confirms your private registry has cached a corrupted version of it. then approach your npm team to clear the cache for that package?

**Comment by cerebrl** [comment]
I'm going to work on your suggestions today. Thank you for the assistance. 

Since this seems like an issue with the internals of our network, rather than this module, I'm going to close it out. I'll ask to have it reopened if for some reason that changes. Thanks again.
